public class Data{
        public String start_date { get; set; }
        public String text { get; set; }
        public Boolean open { get; set; }
        public Integer duration { get; set; }
        public Decimal progress { get; set; }
        public Integer order { get; set; }
        public Long id { get; set; }
        public string type { get; set;}
        public string parent { get; set;}
    }